version: "3.8"

services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest

  nginx-example2:
    container_name: nginx-example2
    image: nginx:latest

  nginx-example3:
    container_name: nginx-example3
    image: nginx:latest

  mongo-example:
    image: mongo:latest
    container_name: mongo-example