FROM alpine:3.9
LABEL authors="ahmadroni"
LABEL company="BWS"
LABEL homepage="https://www.bws.com"
LABEL appName="Docker Sample"

RUN mkdir "hello"
RUN echo "Hello World" > "hello/hello.txt"
CMD cat "hello/hello.txt"