version: "3.8"

services:

  mongo-example:
    image: mongo:latest
    container_name: mongo-example
    ports:
      - "27017:27017"
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssW0rd32!
      MONGO_INITDB_DATABASE: sample_db
    volumes:
      - type: bind
        source: "./data/mongo-data"
        target: "/data/db"
        read_only: false

  mysql-example:
    image: mysql:latest
    container_name: mysql-example
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssW0rd32!
      MYSQL_DATABASE: sample_db
    volumes:
      - type: bind
        source: "./data/mysql-data"
        target: "/var/lib/mysql"
        read_only: false
