version: "3.8"

volumes:
  mysql-data:
    name: mysql-data
  mongo-data:
    name: mongo-data

services:
  mysql-example:
    image: mysql:latest
    container_name: mysql-example
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssW0rd32!
      MYSQL_DATABASE: sample_db
    volumes:
      #- "mysql-data:/data/mysql-data"
      - type: volume
        source: mysql-data
        target: "/var/lib/mysql"
        read_only: false
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 512M
        limits:
          cpus: "0.5"
          memory: 1024M

